#!/usr/bin/env python
import sys
import subprocess

fileName = sys.argv[1]
execFile = fileName[:-4]
outFile = execFile + '.o'

#g++ -std=c++11 test.cpp ==> g++ -std=c++11 fileName
subprocess.call('g++ -std=c++11 -c '+fileName, shell=True)

args = ' -lGL -lGLU -lglfw3 -lX11 -lXxf86vm -lXrandr -lpthread -lXi -lGLEW -ldl -lXcursor -lXinerama'
subprocess.call('g++ '+ outFile +' -o ' + execFile + args , shell = True)
